

use "lib/ht.yap"
use "lib/dyn.yap"
use "lib/fs.yap"
use "lib/mem.yap"


seq Ctx::Global
{
    OUTPUT,  // output asm buffer
    PATHS,   // all included paths, prevent circular import

    LOCAL,   // current local compilation context 
    FRESH,   // fresh label generator index

    STRINGS, // strings constants
    STATICS, // static buffers
    CONSTS,  // constants generated by `seq` blocks
}

seq Ctx::Local
{
    FN_NAME,
    VARS,
    ALLOCER,
}



fn Ctx::MakeGlobal()
{
    put ctx = Chunk::New(Ctx::Global);

    put ctx.Ctx::Global::OUTPUT  = Dyn::Create();
    put ctx.Ctx::Global::PATHS   = HT::Create();

    put ctx.Ctx::Global::LOCAL   = Mem::NULL;
    put ctx.Ctx::Global::FRESH   = 0;

    put ctx.Ctx::Global::STRINGS = HT::Create();
    put ctx.Ctx::Global::STATICS = HT::Create();
    put ctx.Ctx::Global::CONSTS  = HT::Create();

    return ctx;    
}


fn Ctx::MakeLocal(fn_name)
{
    put ctx = Chunk::New(Ctx::Local);
    put ctx.Ctx::Local::FN_NAME = fn_name;
    put ctx.Ctx::Local::VARS    = HT::Create();
    put ctx.Ctx::Local::ALLOCER = 0;
    return ctx;
}


fn Ctx::Emit(ctx, pattern, args)
{
    static 4096 ~ buffer;
    Str::Format(buffer, pattern, args);

    Dyn::Push(
        ctx.Ctx::Global::OUTPUT,
        Str::Copy(buffer),
    );
}

fn Ctx::Write(ctx, path)
{
    put output = Dyn::Join(ctx.Ctx::Global::OUTPUT, "\n");
    FS::Write(path, output);
    Chunk::Void(output);
}


fn Ctx::VarAlloc(ctx, name)
{
    put local = ctx.Ctx::Global::LOCAL;
    put vars = local.Ctx::Local::VARS;

    jump already_allocated ~ HT::Has(vars, name);

    // compute address and increment allocation counter.
    // needs to be pre-inc'd because rbp-addr
    // runs in revserve.
    put allocer = (local.Ctx::Local::ALLOCER) + 1;
    put addr = allocer * Config::WORD_SIZE;
    put local.Ctx::Local::ALLOCER = allocer;

    HT::Set(vars, name, addr);

lab already_allocated;
}

fn Ctx::VarLookup(ctx, name)
{
    put local = ctx.Ctx::Global::LOCAL;
    put vars = local.Ctx::Local::VARS;
    return HT::Get(vars, name);
}

fn Ctx::VarExists(ctx, name)
{
    put local = ctx.Ctx::Global::LOCAL;
    put vars = local.Ctx::Local::VARS;
    return HT::Has(vars, name);
}


fn Ctx::VoidLocal(local_ctx)
{
    HT::Void(local_ctx.Ctx::Local::VARS);
    Chunk::Void(local_ctx);
}

fn Ctx::RenderLabel(ctx, lab_name)
{
    put local = ctx.Ctx::Global::LOCAL;
    put fn_name = local.Ctx::Local::FN_NAME;

    // __local_{fn_name}_{lab_name}\0
    // 12345678         9          10
    put len = 10 + Str::Len(fn_name) + Str::Len(lab_name);

    put final = Chunk::New(len);
    Str::Format(final, "__local_%s_%s", [fn_name, lab_name]);

    put final.(len-1) = '\0';
    return final;
}

fn Ctx::Fresh(ctx)
{
    // prolly enough X3
    put final = Chunk::New(128);

    put id = ctx.Ctx::Global::FRESH;
    Str::Format(final, "__fresh_%d", [id]);
    put ctx.Ctx::Global::FRESH = id + 1;

    return final;
}


fn Ctx::VoidGlobal(ctx)
{
    put output = ctx.Ctx::Global::OUTPUT;
    put i = 0; 
    lab loop;
        Chunk::Void(Dyn::Ptr(output).i);
        put i = i + 1;
    jump loop ~ i < Dyn::Size(output);
    Dyn::Delete(output);

    HT::Void(ctx.Ctx::Global::PATHS);

    HT::Void(ctx.Ctx::Global::STRINGS);
    HT::Void(ctx.Ctx::Global::STATICS);
    HT::Void(ctx.Ctx::Global::CONSTS);

    Chunk::Void(ctx);
}
