

use "lib/ht.yap"
use "lib/dyn.yap"
use "lib/fs.yap"
use "lib/mem.yap"


seq Ctx::Global
{
    OUTPUT, // output asm buffer
    PATHS,  // all included paths, prevent circular import
    CONSTS, // constants generated by `seq` blocks
    LOCAL,  // current local compilation context 
}

seq Ctx::Local
{
    FN_NAME,
    VARS,
    ALLOCER,
}



fn Ctx::MakeGlobal()
{
    put ctx = Chunk::New(Ctx::Global);
    put ctx.Ctx::Global::PATHS  = HT::Create();
    put ctx.Ctx::Global::CONSTS = HT::Create();
    put ctx.Ctx::Global::OUTPUT = Dyn::Create();
    put ctx.Ctx::Global::LOCAL  = Mem::NULL;
    return ctx;    
}


fn Ctx::MakeLocal(fn_name)
{
    put ctx = Chunk::New(Ctx::Local);
    put ctx.Ctx::Local::FN_NAME = fn_name;
    put ctx.Ctx::Local::VARS    = HT::Create();
    put ctx.Ctx::Local::ALLOCER = 0;
    return ctx;
}


fn Ctx::Emit(ctx, pattern, args)
{
    static 4096 ~ buffer;
    Str::Format(buffer, pattern, args);

    Dyn::Push(
        ctx.Ctx::Global::OUTPUT,
        Str::Copy(buffer),
    );
}

fn Ctx::Write(ctx, path)
{
    put output = Dyn::Join(ctx.Ctx::Global::OUTPUT, "\n");
    FS::Write(path, output);
    Chunk::Void(output);
}


fn Ctx::VarAlloc(ctx, name)
{
    put local = ctx.Ctx::Global::LOCAL;
    put vars = local.Ctx::Local::VARS;

    jump already_allocated ~ HT::Has(vars, name);

    // compute address and increment allocation counter
    put allocer = local.Ctx::Local::ALLOCER;
    put addr = allocer * Config::WORD_SIZE;
    put local.Ctx::Local::ALLOCER = allocer + 1;

    HT::Set(vars, name, addr);

lab already_allocated;
}

fn Ctx::VarLookup(ctx, name)
{
    put local = ctx.Ctx::Global::LOCAL;
    put vars = local.Ctx::Local::VARS;
    return HT::Get(vars, name);
}

fn Ctx::VarExists(ctx, name)
{
    put local = ctx.Ctx::Global::LOCAL;
    put vars = local.Ctx::Local::VARS;
    return HT::Has(vars, name);
}


fn Ctx::VoidLocal(local_ctx)
{
    HT::Void(local_ctx.Ctx::Local::VARS);
    Chunk::Void(local_ctx);
}


fn Ctx::LocalSave(ctx)
{
    put local = ctx.Ctx::Global::LOCAL;

    put vaddr = 0;
    lab loop;
        jump done ~ vaddr == local.Ctx::Local::ALLOCER;
        put addr = vaddr * Config::WORD_SIZE;
        put vaddr = vaddr + 1;

        Ctx::Emit(ctx, "push qword [vars + %d]", [addr]);
        jump loop;
    lab done;
}

fn Ctx::LocalRestore(ctx)
{
    put local = ctx.Ctx::Global::LOCAL;

    put neg_vaddr = 0;
    lab loop;
        jump done ~ neg_vaddr == local.Ctx::Local::ALLOCER;
        put vaddr = ((local.Ctx::Local::ALLOCER) - 1) - neg_vaddr;
        put addr = vaddr * Config::WORD_SIZE;
        put neg_vaddr = neg_vaddr + 1;

        Ctx::Emit(ctx, "pop qword [vars + %d]", [addr]);
        jump loop;
    lab done;
}


fn Ctx::RenderLabel(ctx, lab_name)
{
    put local = ctx.Ctx::Global::LOCAL;
    put fn_name = local.Ctx::Local::FN_NAME;

    // __local_{fn_name}_{lab_name}\0
    // 12345678         9          10
    put len = 10 + Str::Len(fn_name) + Str::Len(lab_name);

    put final = Chunk::New(len);
    Str::Format(final, "__local_%s_%s", [fn_name, lab_name]);

    put final.(len-1) = '\0';
    return final;
}


