

use "lib/ht.yap"
use "lib/dyn.yap"
use "lib/fs.yap"
use "lib/mem.yap"

use "src/ir.yap"

seq Ctx::Global
{
    IR_ROOT,  // IR::Node
    IR_ITER,  // IR::Node
    OUTPUT,   // buffer for output binary

    PATCH_MAIN, // address of main call in header stub
    PATCH_FILE_SIZE,
    PATCH_MEM_SIZE,

    DEF_TABLE,  // HT<Str, IR::Node> (function name -> ref node)
    CALL_TABLE, // Dyn<IR::Node>     (call nodes)

    PATHS,   // all included paths, prevent circular import

    LOCAL,   // current local compilation context 
    CONSTS,  // constants generated by `seq` blocks
}

seq Ctx::Local
{
    LAB_TABLE, // HT<Str, IR::Node> (label name -> ref node) 
    JMP_TABLE, // Dyn<IR::Node>     (jump nodes)

    FN_NAME,
    VARS,
    ALLOCER,
}

fn Ctx::LinkLocal(ctx)
    // replaces ARG field in IR::Node for jumps,
    // by a pointer to the REF node.
    // this can only be done after the function is compiled,
    // because only then are all labels known.
{
    put local = ctx.Ctx::Global::LOCAL;
    put lab_table = local.Ctx::Local::LAB_TABLE;
    put jmp_table = local.Ctx::Local::JMP_TABLE;

    put i = 0;
    lab loop;
        jump done ~ i == Dyn::Size(jmp_table);
        put jmp_node = Dyn::Ptr(jmp_table).i;
        put i = i + 1;

        put lab_name = jmp_node.IR::Node::ARG;
        jump label_not_def_error ~ Bool::Not(HT::Has(
            lab_table, lab_name,
        ));

        put ref_node = HT::Get(lab_table, lab_name);
        put jmp_node.IR::Node::ARG = ref_node; 

        jump loop;

lab label_not_def_error;
    Error::PrintError("Label `%s` used in function `%s` but is not defined", [
        lab_name, local.Ctx::Local::FN_NAME,
    ]);

lab done;
}

fn Ctx::LinkGlobal(ctx)
    // this does the same thing as LinkLocal,
    // but for function def/calls instread.
{
    put def_table = ctx.Ctx::Global::DEF_TABLE;
    put cal_table = ctx.Ctx::Global::CALL_TABLE;

    put i = 0;
    lab loop;
        jump done ~ i == Dyn::Size(cal_table);
        put cal_node = Dyn::Ptr(cal_table).i;
        put i = i + 1;

        put fn_name = cal_node.IR::Node::ARG;
        jump fn_not_def_error ~ Bool::Not(HT::Has(
            def_table, fn_name,
        ));

        put ref_node = HT::Get(def_table, fn_name);
        put cal_node.IR::Node::ARG = ref_node; 

        jump loop;

lab fn_not_def_error;
    Error::PrintError("Function `%s` is called but not defined", [
        fn_name,
    ]);

lab done;
}

fn Ctx::MakeGlobal()
{
    put ctx = Chunk::New(Ctx::Global);

    put ir_root = Chunk::New(IR::Node);
    put ctx.Ctx::Global::IR_ROOT = ir_root;
    put ctx.Ctx::Global::IR_ITER = ir_root;
    put ctx.Ctx::Global::OUTPUT  = Dyn::Create(); 

    put ctx.Ctx::Global::DEF_TABLE  = HT::Create();
    put ctx.Ctx::Global::CALL_TABLE = Dyn::Create();

    put ctx.Ctx::Global::PATHS   = HT::Create();

    put ctx.Ctx::Global::LOCAL   = Mem::NULL;
    put ctx.Ctx::Global::CONSTS  = HT::Create();

    return ctx;    
}

fn Ctx::MakeLocal(fn_name)
{
    put ctx = Chunk::New(Ctx::Local);
    put ctx.Ctx::Local::LAB_TABLE = HT::Create();
    put ctx.Ctx::Local::JMP_TABLE = Dyn::Create();

    put ctx.Ctx::Local::FN_NAME = fn_name;
    put ctx.Ctx::Local::VARS    = HT::Create();
    put ctx.Ctx::Local::ALLOCER = 0;
    return ctx;
}

fn Ctx::VarAlloc(ctx, name)
{
    put local = ctx.Ctx::Global::LOCAL;
    put vars = local.Ctx::Local::VARS;

    jump already_allocated ~ HT::Has(vars, name);

    // compute address and increment allocation counter.
    // needs to be pre-inc'd because rbp-addr
    // runs in revserve.
    put allocer = (local.Ctx::Local::ALLOCER) + 1;
    put addr = allocer * Config::WORD_SIZE;
    put local.Ctx::Local::ALLOCER = allocer;

    HT::Set(vars, name, addr);

lab already_allocated;
}

fn Ctx::VarLookup(ctx, name)
{
    put local = ctx.Ctx::Global::LOCAL;
    put vars = local.Ctx::Local::VARS;
    return HT::Get(vars, name);
}

fn Ctx::VarExists(ctx, name)
{
    put local = ctx.Ctx::Global::LOCAL;
    put vars = local.Ctx::Local::VARS;
    return HT::Has(vars, name);
}

fn Ctx::VoidLocal(local_ctx)
{
    HT::Void(local_ctx.Ctx::Local::VARS);
    Chunk::Void(local_ctx);
}

fn Ctx::VoidGlobal(ctx)
{
    // TODO: reimplement this, when done with backend
    Chunk::Void(ctx);
}

fn Ctx::Output(ctx, path)
{
    put output = ctx.Ctx::Global::OUTPUT;

    // delete file, if exists
    syscall(SYSCALL::UNLINK, path);

    // create with all perms
    put fd = syscall(SYSCALL::OPEN
        FS::ConvertPath(path), 
        FS::Mode::WRONLY |
        FS::Mode::CREATE |
        FS::Mode::TRUNC,
        511, // 0o777
    );

    put file = Chunk::New(Dyn::Size(output));
    Mem::ToBytes(file, Dyn::Ptr(output), Dyn::Size(output));
    Sys::TryCall(
        "output",
        SYSCALL::WRITE,
        fd,
        file,
        Dyn::Size(output),
    );

    Chunk::Void(file);
}

